### PR TITLE
Remove executable flags for text files

### PR DESCRIPTION
**Pull request by dhimmel**
cognoma/machine-learning@34225ccdefa191287ca153fc14c73bb4eaa6706d accidentally changed the mode of these files. Revert mode to state prior to cognoma/machine-learning#25.

### CODE REVIEW

**Comment by dhimmel** [comment]
@yl565 does this look good to you? For more information, see https://github.com/cognoma/machine-learning/pull/25#issuecomment-237742056.

**Comment by cgreene** [comment]
looks good to me. :+1: most of them aren't of executable types, and the python file doesn't have a line to tell the shell what to execute it with anyway. Don't think they need the execute bit set.

**Comment by yl565** [comment]
Looks good. Could you please let me know how you changed mode back to normal? I wonder why the file mode changed on my computer. Could it caused by the Ubuntu I'm using?

**Comment by dhimmel** [comment]
> Could you please let me know how you changed mode back to normal?

```
chmod -x LICENSE.md
```

> Could it caused by the Ubuntu I'm using?

No. Most of us also use Ubuntu. Perhaps you ran some `chmod` command in recursive mode.

**Pull request merged**
