### PR TITLE
Upload dask-searchCV notebook

### PR DESCRIPTION
**Pull request by rdvelazquez**
This PR continues on PR #98.

The notebook shows the implementation of dask-searchcv to speed up the pipeline and allow for implementing PCA in cross-validation. This PR is the first step in addressing Issue #94 ... The next step will be to implement dask-searchcv in the main notebooks after #93 is merged.

### CODE REVIEW

**Comment by dhimmel** [comment]
What version of dask-searchcv did you use? We will need to add this to our environment.

**Comment by rdvelazquez** [comment]
I followed the instructions from the [dask/dask-searchcv](https://github.com/dask/dask-searchcv) github page:
```
# Install with conda
$ conda install dask-searchcv -c conda-forge
```

When I list my packages installed in anaconda it shows :
```
dask 0.14.3
dask-searchcv 0.0.2
```

**Comment by rdvelazquez** [comment]
> We will need to add this to our environment.

Should I open a new pull-request to add dask-searchcv to environment.yml and to the main notebooks or should that be part of this PR? Also, I don't know if the notebook currently in this PR is really a necessary addition (it was more just my own evaluation of dask-searchcv) so I'm fine with leaving this notebook out and just focusing on implementing dask-searchCV in the main notebooks. Just let me know.

**Comment by dhimmel** [comment]
> Also, I don't know if the notebook currently in this PR is really a necessary addition

I think it's appropriate in `explore`. I'll merge this now. You can do another PR to implement dask-searchcv in the main notebooks and add it to the environment. I'd suggest waiting until we merge https://github.com/cognoma/machine-learning/pull/100 and then starting your PR from there.

**Pull request merged**
