### PR TITLE
adding machine learning example

### PR DESCRIPTION
**Pull request by gwaybio**
Here is an example classifier for what Project Cognoma will eventually be able to do for any gene, any tissue, and any machine learning classifier.

The classifier is a logistic regression classifier with an elastic net penalty. This simple classifier, with little tuning, predicts 'TP53' mutation status with 97% accuracy in a hold out set. TP53 is the most abundantly mutated gene and massively affects transcription - therefore, it is a good positive control

### CODE REVIEW

**Comment by dhimmel** [comment]
`pd.Series(Y['TP53'], index=Y.index)` is equivalent to `Y['TP53']` I believe. Also should be `Y[GENE]`?

**Comment by gwaybio** [comment]
Yes, nice catch @dhimmel - I will update the PR to fix this change in the next commit

**Comment by dhimmel** [comment]
Assigning @stephenshank to review this pull request. See https://github.com/cognoma/machine-learning/issues/4#issuecomment-235098910

**Comment by dhimmel** [comment]
I wouldn't hardcode the gene into the variable name (`Y_p53`). Perhaps you could switch `Y_p53` to `y`. I think I've seen lowercase for 1d and uppercase for 2d somewhere... but I forget.

**Comment by stephenshank** [comment]
@gwaygenomics This is very helpful and instructive. In addition to @dhimmel's comments all I would say to add right now are the imports
`from sklearn import preprocessing`
`import matplotlib.pyplot as plt`
for someone who wants to run this and does not automatically load these modules in their environments. After these additions, this notebook ran just fine on my system.

**Comment by gwaybio** [comment]
@stephenshank good point, I will add those to the import and also make the changes @dhimmel suggested. Thanks for the comments!

**Comment by dhimmel** [comment]
@gwaygenomics, you should "Restart & Run All" on your notebook before committing it. Keep it fresh. This way you won't get any of these errors which result from non-linear execution and changed code. This is something that we can have pull request reviewers look out for in the future.

**Comment by gwaybio** [comment]
Ok @stephenshank and @dhimmel - PR is updated! I addressed the `Y_p53` variable, the `y = Y[GENE]` comment, added the two imports, and restarted and reran the kernel. Thanks!

**Comment by dhimmel** [comment]
Great will merge now, so we're ready for tonight's meetup!

**Pull request merged**
