### PR TITLE
Adding Factor Analysis

### PR DESCRIPTION
**Pull request by beelze-b**
Finally got factor analysis to work. 

I was trying to generate all the components to full dimensions and then reducing to the most important components, but the memory constraints were just too large. I tried just using 5000 components, but that took over 2 hours to run. 

Like Yichuan suggested in his code, I just ended up doing 500 components.
Although not too rigorous, it works, and it still provides a boost in performance.

The best hyper parameters for the SGDclassifier were {'alpha': 0.01, 'l1_ratio': 0.1}
with Factor Analysis.

The AUC went from .904 to .939 on the test set.

Runtime was around 20 minutes with about 9 GB of memory used (including all my RAM and some swap space).

### CODE REVIEW

**Comment by dhimmel** [comment]
Can you remove `algorithms/AdaBoost-NabeelSarwar.ipynb` from this pull request? You may have something weird going on since both this pull request and your previous (https://github.com/cognoma/machine-learning/pull/40) were based on your master branch.

Other than that, looks good to me.

**Comment by beelze-b** [comment]
Hi, I removed adaboost from the pull request. It should work fine.

**Comment by dhimmel** [comment]
Nice, one last thing. Can you export `FactorAnalysis-NabeelSarwar.ipynb` to a script by running the following from the `algorithms` directory:

``` sh
jupyter nbconvert --to=script --FilesWriter.build_directory=scripts FactorAnalysis-NabeelSarwar.ipynb
```

**Comment by beelze-b** [comment]
Script is added. Also i won't be able to make tonight as I am waiting for a delivery at home. I can work remotely if I know what is new.

**Review by dhimmel — APPROVED** [review]

**Pull request merged**
