### PR TITLE
Export notebook to .py file for easy diff viewing

### PR DESCRIPTION
**Pull request by dhimmel**
I exported manually, but you can also export all notebooks from the root
directory using:

```
jupyter nbconvert --to=script --FilesWriter.build_directory=scripts *.ipynb
```

### CODE REVIEW

**Comment by dhimmel** [comment]
@cgreene @gwaygenomics and others, I'm looking to get this PR merged quickly, so I can submit a pull request that shows a diff of the notebook's code. Can someone review quickly?

**Comment by cgreene** [comment]
@dhimmel : do you just want us to review that it is the content of the notebook output? If so - it looks like the output to me.

**Comment by dhimmel** [comment]
That you support adding the script version of the notebook to a `scripts` directory.

**Comment by cgreene** [comment]
@dhimmel : gotcha - yes, definitely. Much easier to review than the notebook. 👍

**Pull request merged**
