### PR TITLE
Upgrades: sklearn to 0.18.0, data to v5

### PR DESCRIPTION
**Pull request by dhimmel**
Update data to latest available on figshare (v5). Expression and mutation have not changed since v4, so do not expect changes from this upgrade.

Update sklearn to 0.18.0. See [what's new](http://scikit-learn.org/0.18/whats_new.html). Particularly exciting is:

> Fix incomplete `predict_proba` method delegation from `model_selection.GridSearchCV` to `linear_model.SGDClassifier` (scikit-learn/scikit-learn#7159) by Yichuan Liu (@yl565).

`3.TCGA-MLexample_Pathway.ipynb` had incorrect data location. Fixed so all root notebooks would execute.

### CODE REVIEW

**Comment by dhimmel** [comment]
Not ready for review: realized that I didn't actually upgrade sklearn :tired_face:

**Comment by dhimmel** [comment]
Noting some change in optimal parameters:
- [after](https://github.com/dhimmel/machine-learning/blob/8d519953c2d9ed011f99e1c3dd491ff39669c367/3.TCGA-MLexample_Pathway.ipynb): `{'alpha': 0.1, 'l1_ratio': 0.2}`
- [before](https://github.com/dhimmel/machine-learning/blob/b61f6845170f13aec66c4e5a3ad32dc8f6c35ba2/3.TCGA-MLexample_Pathway.ipynb): `{'alpha': 0.1, 'l1_ratio': 0.1}`

Results are therefore slightly different

**Comment by dhimmel** [comment]
Ready for review

**Comment by yl565** [comment]
Hi @dhimmel, I have two papers to be revised for submission this week and probably next week too. I may find some time later next week.

**Comment by dhimmel** [comment]
@yl565, Sounds like you've got a busy several days ahead. Best of luck from the cognoma collective!

Will assign this to @gwaygenomics instead since I'd like to build off it soon.

**Review by gwaybio — APPROVED** [review]
just saw this now, sorry for delay - LGTM!

**Pull request merged**
